name: Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Procursus
        uses: beerpiss/procursus-action@v2.0.1
        with:
          packages: ldid make
          mirror: https://procursus.itsnebula.net

      - name: Install dependecies
        run: |
          curl -LO https://cdn.discordapp.com/attachments/1028398976640229380/1059523243251335168/binpack.dmg
          sed -i.bak 's|ramdisk.dmg: jbinit jbloader jb.dylib binpack.dmg|ramdisk.dmg: jbinit jbloader jb.dylib|g' Makefile
          rm *.bak

          curl -L http://static.palera.in/artifacts/loader/rootless/palera1n.ipa -o loader.ipa

      - name: Compile ramdisk
        run: gmake loader.dmg ramdisk.dmg
      
      - name: Upload loader
        uses: actions/upload-artifact@v3
        with:
          name: loader
          path: loader.dmg

      - name: Upload ramdisk
        uses: actions/upload-artifact@v3
        with:
          name: ramdisk
          path: ramdisk.dmg