name: Build

on:
  push:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Procursus
        uses: beerpiss/procursus-action@v2.0.1
        with:
          packages: ldid make
          mirror: https://procursus.itsnebula.net

      - name: Install dependecies
        run: |
          curl -LO https://cdn.discordapp.com/attachments/1028398976640229380/1059523243251335168/binpack.dmg
          sudo sed -i.bak -Ee 's/API_UNAVAILABLE\(.*\)//g' $(xcrun -sdk iphoneos --show-sdk-path)//System/Library/Frameworks/CoreFoundation.framework/Headers/CFUserNotification.h
          sudo sed -i.bak -e 's/;}/;/g' $(xcrun -sdk iphoneos --show-sdk-path)//System/Library/Frameworks/CoreFoundation.framework/Headers/CFUserNotification.h
          sudo sed -i.bak -e 's/__UNAVAILABLE_PUBLIC_IOS;/;/g' $(xcrun -sdk iphoneos --show-sdk-path)/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h
          sudo sed -i.bak -e 's/const mach_port_t kIOMasterPortDefault/const mach_port_t kIOSTFUNickChan/' $(xcrun -sdk iphoneos --show-sdk-path)/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h
          sudo sed -i.bak -e 's|a named constant. */|a named constant. */\nextern const mach_port_t kIOMasterPortDefault __API_AVAILABLE(macos(10.0), ios(2.0), watchos(1.0), tvos(9.0));|' $(xcrun -sdk iphoneos --show-sdk-path)/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h

          #curl -L https://nightly.link/palera1n/loader/workflows/build/rootless/palera1n.zip -o loader.zip
          #unzip loader.zip -d .
          #mv palera1n.ipa loader.ipa
          #rm loader.zip

      - name: Compile ramdisk
        run: gmake -j$(sysctl -n hw.ncpu) ramdisk.dmg
      
      #- name: Upload loader
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: loader
      #    path: loader.dmg

      - name: Upload ramdisk
        uses: actions/upload-artifact@v3
        with:
          name: ramdisk
          path: ramdisk.dmg
